=== 12mihai05/recipe-recommender-xml-java/src/main/resources/xml/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:simpleType name="cuisineType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Italian"/>
            <xs:enumeration value="Asian"/>
            <xs:enumeration value="Mexican"/>
            <xs:enumeration value="French"/>
            <xs:enumeration value="Romanian"/>
            <xs:enumeration value="Indian"/>
            <xs:enumeration value="American"/>
            <xs:enumeration value="Mediterranean"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="skillLevelType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Beginner"/>
            <xs:enumeration value="Intermediate"/>
            <xs:enumeration value="Advanced"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="firstName" type="xs:string"/>
                            <xs:element name="lastName" type="xs:string"/>
                            <xs:element name="skillLevel" type="skillLevelType"/>
                            <xs:element name="preferredCuisineType" type="cuisineType"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== 12mihai05/recipe-recommender-xml-java/target/classes/xml/users.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="users.xsd">
                                                
    
    
    
    
    
    
    
    
    
    
    <user>
                                                                                                
        
        
        
        
        
        
        
        
        
        
        <firstName>Pasaroiu</firstName>
                                                                                                
        
        
        
        
        
        
        
        
        
        
        <lastName>Mihai</lastName>
                                                                                                
        
        
        
        
        
        
        
        
        
        
        <skillLevel>Intermediate</skillLevel>
                                                                                                
        
        
        
        
        
        
        
        
        
        
        <preferredCuisineType>Italian</preferredCuisineType>
                                                                                            
    
    
    
    
    
    
    
    
    
    
    </user>
                                                
    
    
    
    
    
    
    
    
    
    
    <user>
                                                                                                
        
        
        
        
        
        
        
        
        
        
        <firstName>Alexia</firstName>
                                                                                                
        
        
        
        
        
        
        
        
        
        
        <lastName>Nica</lastName>
                                                                                                
        
        
        
        
        
        
        
        
        
        
        <skillLevel>Advanced</skillLevel>
                                                                                                
        
        
        
        
        
        
        
        
        
        
        <preferredCuisineType>Asian</preferredCuisineType>
                                                                                            
    
    
    
    
    
    
    
    
    
    
    </user>
                                        
    
    
    
        
    
    
    
        
    
    
    
        



    


    

</users>
